version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - ./zookeeper/zoo.cfg:/conf/zoo.cfg
    ports:
      - "2181:2181"
    volumes:
      - /var/zookeeper/data/version-2
    environment:
      - JMXPORT=9999

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=customer:1:1,audit:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - JMX_PORT=9999

  kafka_jmx_exporter:
    build: ./prometheus-jmx-exporter
    ports:
      - "8080:8080"
    links:
      - kafka
      - zookeeper
    environment:
      - JMX_PORT=9999
      - JMX_HOST=kafka
      - HTTP_PORT=8080
      - JMX_EXPORTER_CONFIG_FILE=kafka.yml

  prometheus:
    ports:
      - 9090:9090/tcp
    image: prom/prometheus:v1.7.1
    volumes:
      - ./mount/prometheus:/etc/prometheus
    links:
      - kafka_jmx_exporter
